version: 2.1

jobs:
  neofetch-job:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Update system and check disk space
          command: |
            apt-get update
            df -h
      - run:
          name: Install neofetch
          command: apt-get install -y neofetch
      - run:
          name: Run neofetch
          command: neofetch

workflows:
  version: 2
  neofetch-workflow:
    jobs:
      - neofetch-job
