version: 2.1

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2204:current # Ubuntu 22.04 virtual machine
    steps:
      - run:
          name: Check Disk Space
          command: df -h # Display disk space usage
      - run:
          name: Update System
          command: sudo apt-get update
      - run:
          name: Install Neofetch
          command: sudo apt-get install -y neofetch
      - run:
          name: Run Neofetch
          command: neofetch # Display system information

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
