version: 2.1

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2204:current # Ubuntu 22.04 virtual machine
    steps:
      - run:
          name: Check Disk Space
          command: df -h # Display disk space usage
      - run:
          name: Update System
          command: sudo apt-get update
      - run:
          name: Install Neofetch
          command: sudo apt-get install -y neofetch
      - run:
          name: Run Neofetch and Save Output
          command: neofetch > output.txt # Save `neofetch` output to a file
      - store_artifacts:
          path: output.txt
          destination: neofetch-output # Save as an artifact with a destination name

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
